# Introduction
The series of challenges pertaining to the organization, sharing and reuse of archaeological data, which are often collectively referred to as the discipline's "curation crisis" or "data deluge", have highlighted the wide array of practices that underlie data's construction, management, dissemination and reuse [@bevan2012a; @huggett2022; @huggett2022a].
Numerous studies have complicated the common imagination of data -- which considers them as concise, corpuscular, discrete and inherently truthful records -- by demonstrating how, in practice, they are actually messy, incomplete and non-reductive [cf. @huggett2022a; @voss2012; @dallas2015; @batist2024a].
In fact, archaeologists create data while anticipating their utility as records that inform certain kinds of analysis, while those who apply data in analytical contexts simultaneously reconcile their own use-cases with the conditions under which the data were originally created [@dallas2015: 190-191].

This is reflected in the ways in which archaeologists reuse data.
@faniel2013 [@atici2013] documented how those who reuse data seek out additional contextual information about the circumstances of a dataset's creation by communicating directly with the dataset's originators, thereby establishing a discursive collaborative tie.
Alternatively, many data analysts who operate at a distance from the contexts in which data originate prefer to trust in the models that give the data concrete structure, thereby offloading the acts of reconciliation to those who produced the data [@huggett2022].
In other words, reusing data involves establishing trust, which can be garnered through mutual understanding of the challenges that had to be overcome to get observations to fit within discrete data structures, or through reliance on mechanisms of control to ensure that data are collected and maintained in a consistent manner.

This paper demonstrates some of the strategies employed to establish trust in data.
Through analysis of one illustrative example of archaeological documentation in fieldwork, I show how data-capture is not merely a sensory experience whereby nature is recorded on a 1:1 basis, but is in fact structured by models and power relations that legitimize data and make them useful.
