# Background
This work builds upon prior studies of archaeological documentation in fieldwork settings, particularly Edgeworth's [-@edgeworth1991: 28] dissertation that documented "the transaction between the subject and the object, as it takes place in the act of discovery," which represented an attempt to ground theoretical discourse concerning the objectivity of the archaeological record in the practical "intersubjective work or labour upon material objects".
This extremely polyvalent work touched on various aspects of archaeological practice, highlighting the collective and discursive process of archaeological knowledge production in various settings.
Edgeworth closely examined the physical acts of excavation, the mindsets of the people doing this work, the sensory and conceptual apparatus through which objects are uncovered and made meaningful, and the social transactions that surround and permeate life on the project.
His work drew attention to the social and professional interactions taking place at an archaeological excavation, and which occur as archaeologists articulate an object as a meaningful or discrete entity and make it official.
Crucially, Edgeworth highlighted how archaeological records are produced through improvised, semi-structured and discursive action, afforded by practical concern and limited by the prior experiences held by those doing the work.

Similarly, @goodwin1994 and @goodwin2010 observed how the formation of concrete records in fieldwork settings relates to the establishment of professional frameworks, which lend authoritative legitimacy to the meanings that archaeologists eventually settled upon.
This touched on similar observations made by @gero1996, who noted how certain ways of delimiting features --- which corresponded with gendered experiences --- were deemed more legitimate than others.
@mickel2021 and @yarrow2008 also showed a strong relationship between the diminished interpretative agency among archaeological labourers (including local labourers and undergraduate students) and their inability to contribute tangible and meaningful documentary records about the things they recover.

@thorpe2012 also argued that the broader social and political circumstances --- neoliberal austerity, in particular --- in which archaeological fieldwork tends to operate significantly effects how interpretations are made and arguments are extended, by effectively curtailing fieldworkers' creative agency.
@huggett2022, @caraher2019, @batist2021 and @batist-alienation similarly draw attention to how digital workflows effectively segregate acts of recording from acts of analysis and interpretation, by putting significant epistemic distance between those who hold creative agency in analytical and interpretive domains and those who occupy the domain of fieldwork; they further demonstrate how the latter is leveraged by the former to produce a clear and concise basis upon which formal analytical methods rest.
Moreover, @batist2024a and @haciguzeller2021 point out that the formal and transactional paradigm that dominates discourse on what data are and how they should be handled poses problems for communicating what was actually encountered while excavating a feature, including tentative thoughts, desires and apprehensions that are left out of official records.

In what follows, I will extend this critique by showcasing the improvised nature of data construction in fieldwork settings and by demonstrating how rough encounters with archaeological remains are stablizied and made more legitimate through documentation practices.
