# Methods and Materials
This paper draws from observations of and interviews with archaeologists at work, as well as the documents that they produced.
Specifically, I articulate how archaeologists enacted various activities and how their actions were situated as part of broader systems of knowledge production.
My involvement with this project constituted a longitudinal investigation of archaeological practice that contributed to my doctoral dissertation [see @batist2023a].

## Case
This paper draws from observations of and interviews with members of an archaeological project, focusing specifically on the pragmatic and multifaceted ways in which participants engage with the project's information system.
This involved recording and interviewing archaeologists as they worked during the summer field seasons from 2017 to 2019 and holding additional interviews between fieldwork sessions.
The project's director also provided access to all documents and records for the purpose of this research.

The project upon which this case is based is a research project comprising excavation of a prehistoric site in Southern Europe.
It is directed by a foreign professor affiliated with a North American university, but who has extensive experience working in the region.
The director coordinates various specialists whom he recruited for their expertise in the interpretation of finds, a number of trench supervisors who lead excavation and data collection activities, and excavators who operate under the guidance of their assigned trench supervisors.

It is a research project involving archaeologists with varying degrees of experience and coming from diverse professional backgrounds, including those with extensive experience in the commercial sector (see the supplementary materials for brief summaries of individuals' background).
It is not a field school, but it does rely to a large extent on labour provided by undergraduate and graduate students, and as such engages in on-the-job training.
The informal and situated learning experiences I was able to observe represent instances of legitimate peripheral participation, whereby newcomers are introduced to the norms and expectations that govern the archaeological community of practice.
These scenarios provide especially clear opportunities to ascertain the value ascribed to observed practices and information outcomes conveyed by teachers and adopted by learners through active and productive tutelage.
There is a strong precedent for this approach to the study of archaeological practice [cf. @everill2007; @goodwin1994; @goodwin2010; @morgan2018], including in contexts of continual, life-long learning among experienced archaeologists [cf. @edgeworth1991; @gero1994; @graham2019].

This project served as one of three cases I investigated for my doctoral dissertation, which documents how archaeological information systems scaffold the collaborative and epistemic commitments that govern professional research practices [@batist2023a].
The observations and elicitations I present in this paper illustrate a specific phenomenon with a more refined scope than what is accounted for in that more comprehensive work and in other research outcomes deriving from it [cf. @batist-alienation; @batist2024a; @batist2021].
As such, this paper draws from a relatively small portion of the entire set of observations and interviews, which largely pertain to fieldwork recording practices, processing and analysis of finds, records management, interdisciplinary collaboration, decisions regarding writing and publication of findings, and discussions of how data and findings are presented, evaluated and revised among broader research communities.

I actively contributed to the project for several years, primarily serving as a database manager.
This afforded me with greater awareness of its organizational and institutional history, including a deeper familiarity with all the people involved, and provided me with a privileged outlook on how team members structure information, how they typically use data, and what circumstantial events or motivating factors frame such concerns.
My continual and participatory engagement with this project allowed me to develop an understanding of the intricate social relations as they developed over time, and enabled me to examine certain methods that are drawn out over the course of several field seasons.

I must emphasize that in case-study research, cases represent discrete instances of a phenomenon relating to a researcher's interest [@ragin1992].
Cases are therefore not the subjects of inquiry, but the vehicles through which phenomena of interest are manifested in an observable way.
I recognize that all archaeological projects are informed by their own histories, memberships, sets of tools, methods, and social or political circumstances, which inform distinct traditions of practice, and that it is not possible to generalize across the whole discipline through a single case study.
In other words, my findings are informed by the informants whose actions and attitudes I sought to articulate, and by my own perspective as a scholar of the culture and practice of archaeology and of the media and infrastructures that support it.
The implication is that commercial archaeology, which comprises the vast majority of archaeological work in North America and Europe, is out of the study's scope, owing to the fact that the case represents a research project and that I have very limited experience with and knowledge about commercial archaeology.
However, see @chadwick1998, @thorpe2012 and @zorzin2015 for similar research pertaining to commercial archaeology which produced complementary findings as those presented here.

That being said, this single case study does articulate some significant factors that contribute to decisions and behaviours that archaeologists commonly make and enact, makes certain underappreciated social and collaborative commitments that underlie common tools and practices more visible, and draws attention to certain patterns of practice that relate to contemporary discourse on the nature of archaeological data and ongoing development of information infrastructures.

## Data
My dataset comprises recorded observations, embedded interviews, retrospective interviews, archaeological documentation, and ethnographic and reflexive fieldnotes.

Observational data comprised records of participants' behaviours as they performed various archaeological activities and take the form of video, audio and textual files.
They enable me to document _how_ practices are performed, in addition to the fact _that_ they are performed.
Moreover, observational data allow me to document what participants actually do as opposed to what they think or say they do.
For instance, I situated activities in relation to broader systems, even when participants are unaware that they are contributing to these systems, in order to consider how activities occurring at various times or in various contexts indirectly relate to, compare with or inform each other.
I observed roughly 66 hours of work from this case, which were typically recorded using three different cameras --- including cameras placed on participants' foreheads --- to obtain different perspectives on the recorded activities.
Some of the primary foci that guided my observations were the processes that result in archaeological records; people's use of information objects or interfaces, which sometimes differ from expected behaviour established through their design; how subjects implemented unconventional solutions or "hacks" to work around problems; how the context of an activity affects its implementation; and how local or idiosyncratic terms, concepts and gestures become established in a research community.

Embedded interviews comprised conversational inquiries with participants in the context of their work, and were meant to account for participants' perspectives regarding how and why they act as they do, given the immediate constraints of the situation at hand. Embedded interviews provided insight into the practicalities of work in the moment, from the perspective of practitioners themselves [@flick1997; @flick2000; @witzel2000].
They are also useful for comparing participants' responses with observational records to interrogate how and why participants' observed actions may differ from the rationales elucidated from embedded interviews.
It is difficult to quantify how much data were collected based on embedded interviews since they occurred while observing work they are therefore difficult to distinguish from the remainder of the interaction.
Embedded interviews focused on how participants identify problems or challenges in their work, and to determine ways to resolve them; how certain people gain recognition as domain experts or authorities with specialized knowledge; how specialists relate their contributions to the contributions of others; and how specialists relate their situated perspectives to centralized knowledge repositories.

Retrospective interviews comprised longer sem-structured interviews outside of work settings with select participants to contextualize data collected by other means and to determine participants' views on more general or relatively unobservable aspects of archaeological research (such as planning, publishing, collaboration, etc).
Participants were selected for interviews based on the potential to triangulate different perspectives on objects, themes or situations whose significance was emerging throughout the research [@morse2019].
I conducted 13 interviews during this case; some included more than one participant, and some participants sat for more than one interview.
Retrospective interviews helped me gain insight into how participants situate themselves as members of and in relation to research communities, which may be characterized by different regimes of value and by different methodological protocols or argumentation strategies.
They were meant to highlight participants' perspectives on the value of various kinds of research outputs, what they value in their work and the work of others, the major constraints and challenges that they and their communities face, and how they might resolve them.

I examined documents and media (such as forms, photographs, labels, databases, datasets, reports, instructional media and field manuals) to gain insight into institutional norms or expectations.
See @batist2024a and @batist-alienation for more in-depth analysis of how people interacted with and valued these documents.
This involved examining documents and media as means for encapsulating and communicating meanings among users across space and over time.
This helped me to understand the vectors through which participants either tacitly form collective experiences or directly collaborate among themselves [@huvila2011; @huvila2016; @yarrow2008].
Document analysis emphasized understanding how document design and media capture protocols anticipate certain methods; how various activities refer to recorded information; the reasons why team members ignore certain equipment and forms of documentation despite their availability; how record-keeping is controlled through explicit or implicit imposition of limitations or constraints; why certain records play more a more central role than others; and how different archaeologists record the same objects in different ways.

Finally, my field notes comprised reflexive journal entries that I wrote between observational sessions or interviews.
They also include moments from observational sessions or interviews that I deemed particularly important, as well as descriptive accounts of unrecorded activities or conversations that I have since deemed useful data in their own right.

I obtained informed consent from all individuals included in this study in compliance with the University of Toronto's Social Sciences, Humanities, and Education Research Ethics Board, Protocol 34526.
In order to ensure that participants could speak freely about their personal and professional relationships while minimizing risk to their personal and professional reputations, I committed to refrain from publishing any personally identifying information.
I refer to all participants, affiliated organizations, and mentioned individuals or organizations using pseudonyms.
I also edited visual media to obscure participants' faces and other information that might reveal their identities, and took care to edit or avoid using direct quotations that were cited in other published work that follows a more permissive protocol regarding the dissemination of participants' identifying information.

## Analysis
I analyzed recorded observations and interviews, and interrogated the roles and affordances of various tools and documents, using qualitative data analysis methods.
More specifically, I draw from the "constellation of methods" that @charmaz2014 [: 14-15] associated with grounded theory, namely coding and memoing.
Coding involves defining what data are about in terms (or codes) that are relevant to the theoretical frameworks that inform my research, and identifying instances of these concepts (codings) as they appear throughout the text [@charmaz2014: 43].
Memoing entails more open-ended exploration and reflection upon latent ideas in order to crystallize them into new avenues to pursue, and constitutes a relatively flexible way of engaging with data and serves as fertile ground for honing new ideas [@charmaz2014: 72].
By creating memos that relate and elaborate series of encoded observations and that situate observed experiences in relation to broader theoretical frameworks, I was able to form more robust and thematic arguments about the phenomena of interest while remaining firmly grounded in the empirical data.
See @batist2024a [: 9-10] for a more comprehensive overview of the analytical methods employed for the project from which this paper emerges.

Codes were generated through iterative analysis of recorded observations, transcribed interviews and scans of documents and field notes.
An initial "open" coding phase involved generating codes in a rather open-ended manner to identify common themes and sensitizing concepts [@bowen2006; @charmaz2014: 30-31].
Subsequent coding was scaffolded by a provisional taxonomic code system, which was informed by a loose conceptual model, which broadly encompasses codes about specific activities, participants' figurations, and theoretical concepts concerning the collective constitution of scientific knowledge [see @batist2023a: Appendix B for an overview of the code system].
The study is therefore aligned with Charmaz's [-@charmaz2000] constructivist approach to grounded theory, in that it orients the work by the analyst's prior understandings, rather than have the codes emerge organically.

I refer to specific observations or interview segments throughout the rest of this text using endnotes, which are indexed in the supplementary materials.
