# Discussion and Conslusion
This paper's findings demonstrate how the production of stable and concrete archaeological records involves characterizing the phenomena of interest in nominal terms, while downplaying the situated and embodied experiences that informed the records' creation.
More specifically, it documents a tendency toward enforcing formally-defined records in support of analytical tasks down the line, which present fieldwork as a means to an end, and fieldworkers as instruments that can be wielded to support future analytic endeavours.
It shows how these values are instilled through the social and material experiences in which fieldwork is embedded, which inform fieldworkers about how their labour, and the outcomes of their labour, contribute to collective efforts.
In other words, it reveals how the management of archaeological data and of archaeological labour are inherently intertwined, and draws attention to some mechanisms through which certain voices are rendered more visible than others when constituting the archaeological record.

Moreover, the fieldworkers I observed and spoke with played into the roles they were assigned, even though this meant having less creative agency.
In fact, they generally valued their contributions as sensory devices, which is linked to the notion that they were capable of seeing things as they really are --- as material entities that have seemingly not yet been ascribed stable meaning.
As such, fieldworkers actively contributed to honing the illusion of their objectivity, which enhanced their value as members of the project and as domain specialists with their own unique mental skills.
At the same time, it was also clear that fieldworkers knew, on an intuitive level, that any claim of objectivity is overstated [as per complementary work published in @batist2024a: 12].
However, their positions as responsive rather than creative actors ensured that they are not responsible for resolving this tension [cf. @batist-alienation].

These findings complement other empiritical research examining archaeological data management as collective interpretive action.
For instance, @batist2021 and @batist-alienation note that rote fieldwork practices tend to be assigned to relatively junior project personnel, who become ensnared in workflows which discipline their actions.
Similarly, @morgan2018, who compare analog and digital field drawing techniques, reveal how the act of transcribing archaeological deposits on a blank surface produces greater understanding in the minds of students than participating as a cog in a broader digital apparatus, owing to different degrees of creative interpretive agency that each method affords them.
Moreover, @yarrow2008, who examines the meaning, materiality and agency in archaeological recording practices, draws attention to expressions of resignation among fieldworkers who were more aware that the information they record does not hold special meaning, based on their prior undestanding of how these records would actually be used down the line.
@thorpe2012, @zorzin2010, @edgeworth1991 and @watson2019 highlight similar perspectives in their critical investigations of agentic relationships and knowledge production in commercial archaeology.

This paper has clear implications for thinking about data documentation and the potential for data to be re-used in secondary research contexts, at distance from their contexts of creation.
Surveys by @faniel2012 [: 299-301], @atici2013 [: 676-677], @kansa2013 [: 90-91] and @chapman2016 [: 213], which investigated the needs of data re-users, highlighted their desires to communicate directly with datasets' creators to ascertain the subtext hidden between the lines of their formal documentation.
This aligns with investigations of attempts to enhance archaeological documentation by @huvila2022b, @austin2024 and @opitz2021, which suggest that such efforts should be directed by specific contexts of re-use.
A common thread across these investigations on either end of the archive is that effective data-sharing must involve some discursive relationship between those who produce and re-use data, thereby bridging the epistemic distance imposed by layers of abstraction [@huggett2022a].
Strategies for enhancing data's re-use potential across the continuum of archaeological practice thereby embody Dallas' [-@dallas2015] notion of curation as simultaneous acts of reconciliation and anticipation, whereby meanings are negotiated in relation to prior and future objectives and circumstances.

However, the systemic drive to produce certain kinds of information outcomes based on confident and stable data sources is not fully compatible with this need to acknowledge the complex and storied histories of data.
This tension between distinct notions of data, as concrete and disembodied records in one sense, and as situated products of decisions, actions and circumstances in another, produces an epistemic anxiety that archaeologists must cope with.
It is unclear how, or even if, this epistemic tension can be resolved, but the drive to achieve a state of objectivity in fieldwork, which is facilitated by systemic distributions of agency, persists --- in spite of this outcome's impossibility --- as one coping mechanism.

To be clear, this is not necessarily a bad thing; the instrumentalization of archaeological labour is often necessary in order to derive concrete and confident records that are suitable for analytical methods which comply with modern scientific quality standards.
Moreover, information commons, such as the pool of knowledge accumulated throughout an archaeological project, do not necessarily have to be egalitarian, and are always governed by norms and expectations concerning who may contribute to and extract from communal resources, and in what ways these interactions should occur.
But rather than lean in to the illusion of archaeological objectivity, which is a value built in to most contemporary data management systems, it may be prudent to try an alternative approach that fosters a commensal attitude toward data; namely, one which more fully recognizes data work occurring throughout the continuum of archaeological practice, including in domains that are not typically recognized for their capacity to work with data, such as fieldwork.
