# Supplementary Materials
Supplementary materials for "Balancing Situated and Objective Representations in Archaeological Fieldwork" by Zachary Batist and published in _Advances in Archaeological Practice_.

This document includes two sections:

- A summary of the participants' backgrounds.
- Extracts of specific observations and interviews referenced throughout the paper.

<!-- This document is also available on Knowledge Commons at [DOI]. -->

## Summary of Participants' Roles and Backgrounds
Here is a list and brief description of individuals mentioned throughout the paper:


**Basil:** Project director and faculty member at a North American university.
He has extensive field experience and has consulted as a lithics specialist for various other projects, where he met many of the people who became involved with the project that he now leads.

**Jane:** One of Basil's top students, who joined the project for one season.
As a very independent and competent worker, she took on supervisory responsibilities and stood out as an exemplary fieldworker.

**Theo:** Commercial archaeologist, recommended to Basil by a mutual friend.
An excavator by profession, his competence often serves as an example for the rest of the crew.
He became field director after a few years working as a trench supervisor.
He is very laid back and has a casual attitude.

**Ben:** One of Basil's top students, who joined as a trench assistant.
He came back the following year as a trench supervisor.

**Alfred:** Senior graduate student working at the project for his geoarchaeology dissertation at a North American university.
At a certain point he took on the role of field director.
He is confident, with a hands-on, get-things-done attitude.

---

Here is a list and brief description of individuals mentioned throughout the referenced materials but who
do not appear in the main section of the paper:

**Dorothy:** Senior graduate student who oversees palaeobotanical analysis, including sample collection and processing protocols.

**Jolene:** Senior graduate student who oversees the analysis of chipped stone for the project. She met Basil while working at another project.

**Agatha:** Graduate student who serves as Jolene's assistant. Her specialty is ground-stone artefacts but in this project she largely performs logistical duties.

**Talia:** Junior faculty member who became involved with the project as a trench supervisor after a colleague recommended her to Basil.

**Lauren:** Graduate student who became involved with the project as a trench supervisor after a colleague recommended her to Basil.

**Lester:** Commercial archaeologist who became involved with the project as a trench supervisor after Theo recommended him to Basil.

**Olivia:** Commercial archaeologist who became involved with the project as a trench supervisor after Alfred recommended her to Basil.

## Observations and Elicitations
##### A1 {#sec-A1}
**Jane:** Approaching another context, I think.\
**Zack:** Why do you think that?\
**Jane:** The texture is changing, and the colour is changing a bit, and umm, there's a layer of big boulders and now there isn't.\
**Zack:** Can you be more specific?\
**Jane:** Well the darker sand is becoming more red, which is similar to what we had there, and then I also noticed that is holds more of a form, like the hearth is very loose, but the sand is more in place, it's almost like if you brushed it, you would get a perfect floor.

##### A2 {#sec-A2}
**Jane:** So, this is like still kind of a dark, dark brown, going into the sand, but it's like really tough, like hard to dig through, kind of. So I think maybe it's just context \[?\]. ((gesturing towards other side of the trench)) And then this is like really light grey, ((bobs hand up and down to emphasize these last three words)) and I thought it was just cuz it had just dried out, and I hadn't done this kind of \[fill\], but it's also really hard to dig, and like a really light grey, so I don't know if it's just remnants of this part, or what\...\
((Basil gets in the trench to take a closer look))\
**Jane:** Or like maybe this is like, would it be possible that that's like an older hearth, like the other one that was leached out?\
**Basil:** Yeah, hmm. So the colour here is the same as what you were digging, but the consistency has changed?\
**Jane:** Yeah\
**Basil:** I would clean up, maybe just straighten that section a bit\
**Jane:** Yeah\
**Basil:** Just to the depth that you started at for this context\
**Jane:** Yeah\
**Basil:** And then we'll clean up and carry on with, you know, we can just write in the text that, you know, these are the differences\
**Jane:** Yeah\
**Basil:** But you know what, after we start to dig it it might change back to something more familiar\
**Jane:** Yeah\
**Basil:** And we can just say oh, it's like some kind of differential lens of material within it\
**Jane:** Right\
**Jane:** Okay. Okay, so just clean up the walls, and then keep going, okay.\
**Basil:** Yeah, but we can photograph, change numbers.\
**Jane:** Oh, okay.\
**Basil:** We'll treat it as something different, you know we can write in the notes that there is a very good chance that it's still the same stuff, but the consistency changed\
**Jane:** Right.\
**Basil:** So, just be careful.

##### A3 {#sec-A3}
**Zack:** Did you feel like there are, like, problems, with communicating, in terms of like understanding, sort of the things that like Alfred was getting at? Or like, if there were any issues in like, uhh, comprehending something that eventually you sort of learned, or were there any sort of challenges in that sense that you had to deal with? Do you recall any examples like that? Especially maybe in the beginning.\
**Jane:** I think for a geology it's best, especially like if you do a couple of geology courses, it's always hard to like train your eyes to see certain things. Like sometimes Alfred would like take out a handful of sand and go like do you see the red flakes? and I would be like no. Or even like, pointing our stratigraphy, like see how this changes to this level, and it just kind of, training your eye to see what they're seeing is, sounds like an easy thing but it's actually hard to like, kind of, pick out things that they want you to pick out. And I think like now it's easier to like, oh, see how that's transitioning, or like, umm, even just like comparing peoples' trenches and like the contexts they're in, it's easier now but at the start it was like, it looks the same to me, or like I don't spot what you're spotting, you know? And it's just a way of looking at things that I think that's the hardest part for me.\
**Zack:** Do you know how that developed?\
**Jane:** I think just like repetitive, like every day, looking at stuff, I think is like, just a good way of learning. I don't know if there's something specific but\... and just hearing from like, hearing Alfred pointing it out, hearing Basil pointing it out, hearing different supervisors pointing it out, it was just different ways of explaining it or showing it to you that it starts to kind of, like, produce a form of knowledge. Umm, but I dunno.

##### A4 {#sec-A4}
**Lester:** And that was the time I really kind of got into excavation as a concept. So I did that on my first year. In my second year, I \[unclear\] community archaeology, and then \[redacted\] field school. \[redacted\] field school is a big part of \[redacted\] University's training program for their students. I didn't receive enough excavation experience in my own degree, so I went and applied and volunteered on that excavation, and then my third year I went back to the same excavation at a supervisor grade.

##### A5 {#sec-A5}
Had a brief convo with Olivia as she was cleaning up, when the corner cam died. I really \[\....\] by the mic. It was about focus, \[awareness?\] of one's surroundings, being in the moment and focusing on the task at hand. Focusing on the little things helps her keep her organized. It is an active strategy in use. She hates that although excavation is manual labour, it really requires you to actively think. You can't just phase out -- \[illegible sentence\]. I mentioned my tendency to compare excavation with tunnel vision, and noted how I think it is somewhat flawed. She asked me if I played a musical instrument, and I said no, and then asked if I could relate to that. She compared these activities in order to convey the sense of being in the moment, facing a task at hand, dealing with what is immediately in front of you, literally and figuratively, and the satisfaction of achieving one's goals and ticking off all the boxes. She likes to set goals, for herself and for others.

##### A6 {#sec-A6}
**Lester:** So, our first week was tough. Very, very tough. We had a very uhh difficult trench to excavate, very hard layers that were very difficult to physically excavate. Uhm and I can dig for a certain extent, for a period of time in quite hot weather, I'm used to this, for this is not a problem. But I see people that have never approached this, attack it physically, really really attack it physically, and not bear in mind that this is actually really difficult. And it's not a physicality thing, it's a, it's a thought process. So it's uhh, yes you're physically able to excavate twenty centimeters in a day, but how are you going to feel at the end of the day? Are you going to be able to identify the context while you're doing it? It's better to excavate ten thoroughly than twenty in a hurry, you know? And, but the speed will come with time. And so I've noticed this with Morris particularly, he was quite, he's a very able archaeologist, a very good digger, uhm but physically he's changed the way he approaches things, so he won't go full-on that \[unclear\] now, and then expect to be able to do it again the following morning. And then equally, the understanding is growing, so like contextual change, uhm, I've really struggled to try and integrate teaching into my methodologies on site, because that's not my skillset, and not what I'm used to. But now I think we've finally figured it, I'm involving him in the paperwork a lot more, making that a part of the teaching process, a bit more. I think it's beneficial.

##### A7 {#sec-A7}
**Ben:** I think just sometimes, like, I've become too self-aware, and I get in my head sometimes.\
**Zack:** While you're digging?\
**Ben:** No, not while I'm digging. Because while I'm digging I'm like generally busy, and I'm like, like listening to music or whatever

##### A8 {#sec-A8}
**Zack:** And uhh, the music is a thing, it frames the mood. I'm trying to think about time and how it frames the day. That's a bit of an idea that I abandoned and that I want to come back to later on. You know, sort of, so I need to observe that earlier on in the season, which I didn't get an opportunity to do.\
**Ben:** Yeah. I'll think about that while I'm out there.\
**Zack:** How about you?\
**Jane:** I'm kind of the same. Like I'd rather just like get going and like continue going. Like umm, often when Kaitlin is near the trench and like Basil's not there she'd be like get out, have a break, or like, Talia likes to be like come out and have a breeze break, but I just would rather like just keep going until lunch. Like it's just, like maybe step out once or twice to get water, but like, I find breaking and like, just kind of like, I like to just start thinking about things and for me it's just kind of like, get lost in digging and doing your shit, and then time passes.\
**Zack:** Do you get lost digging?\
**Jane:** Yeah! I just, like, I started thinking about something and then I'm\... Like it just makes it, like, less of like a, oh when's gonna be my next break? Or like, even like, that's why I'm kind of glad we don't talk or like listen to music, because I feel like that would like frame time more specifically. Whereas like, without any sound it just kind of like comes, time is like insignificant kinda thing.

##### A9 {#sec-A9}
**Basil:** I didn't have music in our trenches, and I think I initially used the excuse that our proximity to umm Gary's house. Although, of course Gary was only there for the last two weeks. I think that it might slightly annoy me if I need to be focused, I find it a distraction. And it's not like it's just in the background. I think, you know, with Theo and those guys, there's dancing, there's singing along, which I, if I was right next to them I think it would drive me bananas. And it probably drove Lauren slightly bananas. Umm, most projects that I've been on, there hasn't been music. Which, back in the day, you know, you would need batteries and \[unclear\] and what have you, and umm, so technologically I think it's easier to have music on site now. Umm. No, but I think there's intimations of it being unprofessional. It's like, it's it's a distraction from what you're doing. In fact, I worked, when I worked at Sutton Hoo back in the day, umm, Philip Rahtz, one of the excavators there, had written a textbook on archaeological field practice, infamous, umm very old fashioned, and he, he had a famous section about, umm uhh, during the excavation, the only sound you should hear is trowel on stone. If you had found something important, you quietly get up, walk over to the supervisor, bring them over, show them, you don't \[unintelligible yelp\], you don't make any \[unclear\]. It should be focused and silent. Now I'm not gonna ever go to that extreme. But uhh, I remember, I think, I mean Alfred, I mean Alfred had umm, well I mean, it's you know, it's like, office environment. Well, no, some office environments do have music on. But umm, umm we had uhh, I think, I mean Alfred had music on in the background. I think he---\
**Zack:** Where? In the rock shelter, you mean?\
**Basil:** Umm, trench \[redacted trench ID\] and when he was over with Maddie. Umm, he always had music. But it was background music for him, umm I don't know how loud or whatever, I--- it doesn't appeal to me. I, I find it a distraction. I can't work here with music. Or if I'm, if I ever have music on it's because I'm writing emails or I'm doing something that I can't be distracted by. Umm, sometimes, you know, I allow myself classical music because it's a foreign language or there's no lyrics for me to be distracted by. Umm I think Alfred was, had a problem with, but maybe he didn't see it as his role to umm make that call, with people being plugged in. So Kaitlin would dig with headphones in. I think a couple other people might do that as well.\ **Zack:** I think Jane did too. Don did.\
**Basil:** Yeah. Umm. And I think Alfred was like, no, you need to be more focused on what you're doing. And it was like, I think like, I didn't feel strongly enough about it, or I felt like the music thing's a bit weird anyway, that I wasn't gonna come down on people. I might think about that for, for next time in terms of\...

##### A1- {#sec-A10}
**Zack:** So I have like one more section. We zoomed through this. I'm wondering about, like, the way you set up, like your research environments, environment or plural. I mean, do you, I've noticed, but maybe you don't, maybe you are less able to recognize certain routines that you get into.\
**Lauren:** Oh, totally, totally.\
**Zack:** Yeah. And I'm sort of wondering if you could explain any of those to me.\
**Lauren:** Umm, I'm a very organized person. I do need that. So for me, umm, packing my backpack the same way every morning, knowing where my things are, sorting stuff out in advance, like taking notes, for myself, in my own notebook, saying tomorrow you need to do this and this and this, and knowing where my notebook is, is very important. So I pack my backpack, either in the evening or in the morning, it doesn't really matter to me. Umm, I know what material or supplies I need, and pack them. I bring them and then when we are on site I always put my backpack in the same place, I take my stuff out in the same, I mean they're not laid out in order or something, but umm, yeah.

##### A11 {#sec-A11}
**Zack:** Okay. But with regards to stratigraphy, do you take into account the other trenches and their stratigraphy?
**Ben:** Oh, right. Yeah. Because I'm close by to \[redacted trench ID\] and a lot of the reason for opening the trench I'm in now, \[redacted trench ID\], uhh was to find similar things as \[redacted trench ID\], I am following, or I am trying to like compare the stratigraphy.

##### A12 {#sec-A12}
**Lauren:** Exactly. Because I write it down. But still, I enjoy these interactions with people in my trench. And also people like, we are, like, in a luxury position on the east side, and we are really close with our trenches, especially Theo and I, so we can talk about what's happening in our trenches, correlate it, and ask each other for opinions.\
**Zack:** How have you, like, how would you, like how has that worked out? Can you give an example?\
**Lauren:** Really good. Usually it's like, umm, Theo sticking his out of his trench and is like, Lauren, do you have a moment? Or me saying, Theo, can you have a look at this? And then umm, we compare, usually we compare, like, our stratigraphy or we look at material, like getting each other's opinion on, I don't know, certain flakes, or umm, types of rocks. So yeah, umm, it's really, really interesting. Obviously, Theo has worked here last year so I've relied on his umm\...

##### A13 {#sec-A13}
**Zack:** How does the feedback you get from Jolene and Agatha and Basil and Alfred help you when you're doing it on your own, or when you're starting from scratch, when you're starting your own trench?\
**Theo:** It just gives you an idea of what to expect. I mean not necessarily with the lithics, but with Basil and Alfred knowing the hill so well, they know what they want and they know what they're looking for. For example, when I was working on \[redacted trench ID\], Basil wanted, the point of that trench was to look for Mesolithic stuff, and to try and find stratified Meso, so umm that, so Basil explained that to me and then I knew what I was looking for. I knew that I was looking for microliths, predominantly, maybe the whiter, the bright white chert, rather than--

##### A14 {#sec-A14}
**Ben:** I have interacted very little with Jolene. I feel that I should interact with her more, because I would like to know like what's going on in my trench. Umm I should probably talk to Agatha as well. Umm, but yeah. I've talked to, I was only here for a few days, well by the time I was supervisor Alfred had already left. So I didn't really ask him about anything. Umm. The only person I've really talked to is Basil, because he's very interested in my stuff, so like he'll come to me and actually give me information, then I will like ask questions.\
**Zack:** What kinds of information does he give you?\
**Ben:** Umm. Uhh just like type of stuff we're finding, uhh\...\
**Zack:** From the apotheke, you mean?\
**Ben:** Yeah, just like the type of artefacts that are coming out of my trench, and he'll give me some examples of like, not what to look for, but like some examples of characteristics that are being found on my, or on the artefacts from my trench. Uhh just like hinge fractures on some of the cores and stuff like that, which are characteristic of--\ **Zack:** How do you make use of that?\
**Ben:** It's, it's easy to like, once you see it, once you see it, right, like if you see a hinge fracture, and like oh okay, that's what a hinge fracture is, and you look at it in the field and you're like, you weren't sure of something, like you weren't sure that it was an artefact, and you see that, you're like oh, that's a hinge fracture, let me take that. So I think it's good to know like that information--\
**Zack:** Because that definitely effects the sieve, like the sieve\...\
**Ben:** Sorry?\
**Zack:** That definitely effects the collection of artefacts\...\
**Ben:** Oh, 100%. Like it could bias it. But any, any prior knowledge you have is going to bias it, right? Like\...

##### A15 {#sec-A15}
**Zack:** What do you think of people like Dorothy, who aren't necessarily working with you?\
**Ben:** What do I think?\
**Zack:** Like have you asked them about their interpretation of your stuff. Do you think that would be helpful to have?\
**Ben:** I think Dorothy is a little bit different, just because hers is like very, like she's working on micro remains and like macro remains, or like\...\
**Zack:** Botanicals.\
**Ben:** Botanical stuff, right. So her stuff is like coming out of the soil that I collect. So there's nothing I can do to effect the amount of stuff she's gonna find. So while it's cool if she finds stuff from my trench, like there's no way that I'm going to effect it and there's no way that she can effect me in finding uhh. I would like to know more, I guess I should also ask her, but I think it's a little bit different because we're not interacting directly with the botanical remains.

##### A16 {#sec-A16}
**Zack:** So umm, I guess I've already got your bio and all that. But I'm wondering if you could reiterate your overall objective of your work. I mean how your work contributes to \[this project\].\
**Theo:** Umm, the objective of my work\...\
**Zack:** Or of your contri-- or of what you're doing here.\
**Theo:** It's to dig holes. Dig holes.\
**Zack:** So maybe a way to get a better answer, can you tell me about the current season and what your current plans are, or have been?\
**Theo:** For this season I've been digging a big hole. Yeah, we aim to finish it, but I doubt we will.

##### A17 {#sec-A17}
**Zack:** So the third theme, and this is the one I'm a little bit, I wasn't sure how your response would uhh, would play out, but are you involved at all in the preparation of data that will be shared externally or openly as addendums or publications, or like via professional networks or like on platforms like the ADS or whatever?\
**Theo:** No.\
**Zack:** No?\
**Theo:** Nope. I'm not an academic.\
**Zack:** But you do-- sorry\...\
**Theo:** I don't get involved in that shit.\
**Zack:** But as someone who, umm, works in commercial archaeology, a lot of ADS has a lot of stuff in commercial archaeology.\
**Theo:** Yeah, but it's not me. I'm not a supervisor in commercial archaeology, I don't write up sites, I just dig holes.\
**Zack:** I thought you were do do commercial, I thought you do dig holes for commercial archaeology.\
**Theo:** Yeah, I do, but I don't write anything up.\
**Zack:** So that's the extent of your involvement then?\
**Theo:** Yeah.\
**Zack:** You get the material.\
**Theo:** Yeah.\
**Zack:** Do you, I mean, so I guess you, it sort of seems like you don't want to be, uhh have any sort of involvement with--\
**Theo:** I would. I would if I was asked. I wouldn't mind. I wouldn't be good at it. It's been a long time since I've written anything properly.

##### A18 {#sec-A18}
**Ben:** Umm, I am not super academic. So that's part of the reason why I'm not like super into the, the--\
**Zack:** The findings?\
**Ben:** No, no not necessarily the findings. Like I find the findings interesting, and like the Levallois stuff, and like the technology, and like the differences and all that. I find that super interesting. But I don't, like the paperwork and all that, like I'm not like, I'm not, I'm not one to like be sitting at a desk just writing all day. Like, I like to be in the trench, I like to be doing something physical and like engaging, right? And I don't, like reading and like articles and like scientific research and stuff, just like, it doesn't interest me, like that much. Even like, I have to be engaged in the topic, you know?\
**Zack:** Yeah, yeah. I feel like you and Theo have a lot in common.\
**Ben:** I think so, yeah. Like Theo describes himself as like I dig holes, and I'm like yeah, I can relate to that, man. Like I dig holes too. Like this stuff is cool, but like, I don't see myself like engaging with it, or like\...

##### A19 {#sec-A19}
**Zack:** Are you familiar with the work of the ADS?\
**Theo:** Yeah.\
**Zack:** Yeah? What do you think about it?\
**Theo:** It's pretty good.\
**Zack:** Yeah.\
**Theo:** I like it, because I can look up sites if I want.\
**Zack:** Do you do that regularly?\
**Theo:** Sometimes. If I'm in, if there's things that I want to read up on. Like, sites I'm working on and stuff from the fields nearby.\
**Zack:** So just out of curiosity.\
**Theo:** Yeah.\
**Zack:** And they have lots of commercial stuff, right?\
**Theo:** Oh yeah.\
**Zack:** What sort of stuff do you look up? Like what do you read?\
**Theo:** It was just, old site reports.\
**Zack:** Like the PDFs, or do you look at the tables, or like if they do photogrammetry, do you look at any of that?\
**Theo:** Ehh it depends. It depends on what there is.\
**Zack:** And it informs you as you work on your own stuff?\
**Theo:** Yeah. It's like, I dunno, I don't use it often. But if you're on a really exciting site and you want to know more about what's happening, then yeah.\
**Zack:** Have you, I mean have you, if you're on the site--\
**Theo:** It's just out of curiosity.\
**Zack:** Are you, but like--\
**Theo:** If you're aware of it, if you're aware of a site that's been excavated, and you've heard that it's supposed to be really good, see if it's on ADS.

##### A20 {#sec-A20}
**Zack:** So I'm not really, like I'm not really as privy on the details of that. Can you briefly describe specifically what the issues were?\
**Theo:** It was just that it was dug poorly.\
**Zack:** How do you mean?\
**Theo:** Well it was like they just went down, they didn't give a shit about the sections or the recording so much. The recording, the more I've done it and looked at it, the happier I am with it.\
**Zack:** From last year's?\
**Theo:** Yeah, from last year.\
**Zack:** Why?\
**Theo:** But it was just initially it's very much like minimal recording. There was minimal recording.\
**Zack:** Why was that gradual, why the more do you look at it the more--\
**Theo:** Well because I have, over the season, gotten more of an understanding of the trench. I've been thinking about it far more, and working out what's going on.\
**Zack:** So that minimal recording sort of made sense as you sort of got to know it?\
**Theo:** Yeah.\
**Zack:** Huh.\
**Theo:** But I mean it could have had more recording, but I mean the bare minimum that was required.\
**Zack:** Can you give an example of that kind of uhh, that kind of poor recording that eventually grew on you? Or that you eventually came to understand, perhaps?\
**Theo:** I don't know. If you go to the other ones\
**Zack:** If you go to the what?\
**Theo:** The more complex stuff, the fact that it, last year it was five lithostratigraphic units and now I've just three.\
**Zack:** Mhm.\
**Theo:** And one unit is just one big mess. It's quite nice. That makes, I think, the mixture of poor recording and over-complicating stuff, that made it difficult to understand to start with, and poor digging.\
**Zack:** So how did he over-complicate things?\
**Theo:** He just like--\
**Zack:** Did he just like split instead of lump?\
**Theo:** Yeah, he split stuff and used terms that he didn't quite necessarily understand. I don't understand them. I made, I got Alfred to explain it to me \[unclear\]\
**Zack:** So, in your view, what sort of, what could have, how would you have avoided this if you were digging that trench last year? How would you have avoided these issues? Or were they avoidable at all??\
**Theo:** Yeah, you could have recorded it better. He could have written more. Had a more thorough notebook. Not-- I'm pretty sure one of the contexts was made up.\
**Zack:** Cleaning context?\
**Theo:** No, no.\
**Zack:** Not even?\
**Theo:** Right in the middle of the season. The only record of it is the context sheets, but yeah. I don't suppose we should actually really talk about all that.\
**Zack:** Okay.\
**Theo:** Like, in honour of professional standard.\
**Zack:** Well that's what I'm hoping to understand.\
**Zack:** We could, we could.\
**Theo:** For the integrity of the project, we shouldn't really talk about the fuck ups, really, should we?

